name: Bug Report Template
description: File a bug report using the Template
title: "[Bug]: "
labels: [BUG]
assignees: "FuryFight3r"
body:
  - type: markdown
    attributes:
        value: |
          > [!CAUTION]
          > First time Creating a Bug Report for Scrapping Simulator? or does all this look New to you?
          > 
          > Please checkout the Link below to ensure that your Report doesn't get closed without a Resolution and to make sure your Report is up to scracth - If you've read this Guide in the past (Prior to April 2024), have another look as it has changed a lot since.
          
          ![How to create an Effective Bug Report](https://i.imgur.com/9ocGiJF.png)

          [### How to create an effective Bug Report](https://github.com/FuryFight3r/ScrappingSimulator/wiki/How-to-Create-an-effective-Bug-Report#first-step)

          > [!IMPORTANT]
          > Reading and Looking for Logs not your thing? Probably best not to waste your time with this report template, instead use the ***In-Game Bug Reporting*** feature using ***[F8]*** to quickly, effectivly and easily create a Bug Report.
          > 
          > If you cannot, or do not want to use the In-Game Bug Reporting feature please describe why in your Report Description, to help me improve it. 

          > [!WARNING]
          > Reports with the tag ***'Pending More Info'*** will be ***closed*** after 1 week of last comment if the missing Info/Logs are not Provided or no response is recieved within the week.
          > 
          > This is to help reduce clutter and the 'Fix my issue... BYEEE' attitude on the Issue Board and keep a priority bias toward ***Well Described/Thorough*** and ***In-Game [F8] Bug Reports***. In short, Help me in helping you.
          >
          > If affected by Report Closure don't fret, simply include the missing information and Re-Open the Issue at your convenience, otherwise consider trying again with the ***In-Game Report [F8] Feature*** to help limit the ability of lacking information as this system does half the work for you and also limits the need for back and forth communication, if you prefer to just report the bug and get back to your life.

          > [!TIP]
          > 
          > If your bug report pertains to an object disappearing or falling through the ground, have you considered checking the Lost & Found Box adjacent to your Personal Computer? 
          > 
          > Additionally, for any other unusual occurrences, consider accessing the Commands panel (accessible via [F1] or Tilde [~/`]), which offers solutions for some known bugs.
          > 
          > If you believe you've discovered the reproduction steps to a Bug on the Commands Panel or to any bug for that matter, please share this to hopefully solve the Root Cause of the Bug, rather than relying on a Command Bandaid to temporarily fix the issue.
          > 
          > Persistent issues requiring frequent command usage for resolution is not typical. Commands are intended as a one-time use to correct/fix broken data, code death loops, or player stuck instances, rather than to serve as a recurring means of repair. If you encounter such issues, consider creating a bug report in relation to this issue.

  - type: dropdown
    attributes:
      label: Have you tried Restarting the Game/Re-Loading?
      options:
        - "Please Select"
        - "No - Please explain why - Provide Logs/Save File"
        - "Yes - Provide Logs/Save File"
        - "Cannot Save/Exit due to bug - Provide Logs/Save File"
    validations:
      required: true

  - type: dropdown
    attributes:
      label: (If 'Yes') what was the outcome after Restarting?
      options:
        - "Please Select"
        - Returned to Normal, But cannot Reproduce the Bug - Provide Logs/Save File & Last Backup File
        - Returned to Normal, But was able to reproduce the Bug again - Clearly describe the steps - Provide Logs/Save File
        - Still Bugged immediately after Reloading the Game - Provide Logs/Save File
        - Even worse after Reloading the Game - Explain how it got worse - Provide Logs/Save File
    validations:
      required: true

  - type: dropdown
    attributes:
      label: How are Decimal Numbers normally Displayed on your Machine In-Game?
      options:
        - "Please Select"
        - "v0.35.6 & $45.75 (Dot Point) - Provide Logs/Save File"
        - "v0,35,6 & $45,75 (Comma) - Provide Logs/Save File"
        - "Neither of the above - Please explain further - Provide Logs/Save File"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear description of what the bug is you experienced - Try Include events leading upto the error.
      placeholder: |
        A good Report Description should include events leading up to the Bug not only just the Bug itself.
        Example of a poorly described bug; 'PC randomly vanished for no reason'
        Example of a well described bug; 'Each time I put a PC onto the Disassembly Desk it Vanishes, I've tried with multiple PCs and each one vanished so it wasnt a random once off, other Items all work fine, Restarting doesnt fix the issue.'
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: Please provide steps to get the same outcome as you - It's rare that a bug 'just happened for no reason' often times there is a cause behind it and even sometimes a very specific series of events involved to recreate the Issue - For example, Saving/Re-Loading can be a great way fix some bugs, but on certain occasions it can be a cause for more issues, so if you recently Saved/Loaded to then find an issue that wasnt there before or the Issue got worse because of this action, consider including this crucial information in your report
      placeholder: |
        EXAMPLE;
        1. Go to the Personal Computer.
        2. Open the Games Folder.
        3. Leave Games Folder Open and exit the PC.
        4. Go to Sleep.
        5. Go back to the Personal Computer.
        6. Games Folder is now gone and cannot be Opened again.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshot(s)/Video(s)
      description: Please upload screenshots and/or links to videos that help illustrate the issue (If unable to provide media type 'Not Applicable' or 'N/A' and **why** (ex; 'I missed the oppurtunity to capture the bug').
      placeholder: |
        Drag your Screenshot(s) below to upload them, Upload your video(s) to a Video Hosting service of choice (ie Youtube) and add the link(s) here.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Player Logs
      description: Please provide your player logs - Unfortunately with a majority of reports lately missing Log Files, and not being able to get back in touch with OPs, this field is now required regardless the type or nature of Bug/Issue encountered - Log Print Outs over time I have designed to be crucial to fixing problems very quickly and effectively, especially User/System Specific Bugs/Issues that are not easily repeatable on all systems/regions.
      placeholder: |
        If you are unsure of where to find your Player Logs or Save File please refer to the [How to create an effective Bug Report](https://github.com/FuryFight3r/ScrappingSimulator/wiki/How-to-Create-an-effective-Bug-Report#first-step) Wiki before creating a Bug Report to ensure your report doesnt get closed without a resolution. Or consider using the In-Game Report [F8] feature which takes out the hard work of Reading and File Gathering for you.
        Please Click here and then Drag your [Player.log] and [Player-prev.log] below to upload the files.
        You can also add your Save-File here by archiving [Player.log], [Player-prev.log] and [Scrapping_Simulator_Data.es3] into a Zip file and dragging it here, or Use the In-Game [F8] Bug Report Feature to have this done automatically.
    validations:
      required: true

  - type: markdown
    attributes:
        value: |          
          > [!CAUTION]
          > Have you made sure to include Crucial Information Such as Logs, Screenshots, Save File, Bug Description, Reproductioon Steps, etc?
          > 
          > Please double check to make sure you are not missing any important information that could help fix your problem quickly.

  - type: dropdown
    attributes:
      label: Are you happy with the content in your report?
      options:
        - "No"
        - "Yes"
    validations:
      required: false
