name: Bug Report Template
description: File a bug report using the Template
title: "[Bug]: "
labels: [BUG]
assignees: "FuryFight3r"
body:
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > First time Creating a Bug Report for Scrapping Simulator? or does all this look New to you?
        > Please checkout the Button Link below to ensure that your Report doesn't get closed without a Resolution.
        > 
        > If you've read this Guide in the past (Prior to April 2024), have another look as it has changed a lot since, it's been Reworked and also now provides some Examples & more Tips to help you make a great Bug Report that likely will be fixed very promptly.

        [![How to create an Effective Bug Report](https://i.imgur.com/9ocGiJF.png)](https://github.com/FuryFight3r/ScrappingSimulator/wiki/How-to-Create-an-effective-Bug-Report#first-step)
        
        > [!TIP]
        > Looking for Logs not your thing? That's cool, try the [***In-Game Bug Reporting***]() feature using ***[[F8]]()*** In-Game (Both Menu and Gameplay) to quickly, effectivly and easily create a Bug Report instead, which can make things a bit easier.
        > 
        > If you cannot use the In-Game Bug Reporting feature please describe why in your Bug Report Description - If you do not wish to use the In-Game Reporting Feature, please create a [[Suggestion]](https://github.com/FuryFight3r/ScrappingSimulator/issues/new?assignees=FuryFight3r&labels=Suggestion&projects=&template=suggestion.yaml&title=%5BSuggestion%5D%3A+%3CAdd+Title+Here%3E) on how I can improve it and make it easier. 

        ---

        # Bug Report

  - type: dropdown
    attributes:
      label: Have you tried Reloading?
      options:
        - "Please Select"
        - "No - Please explain why - Provide Logs/Save File"
        - "Yes - Provide Logs/Save File"
        - "Cannot Save/Exit due to bug - Provide Logs/Save File"
    validations:
      required: true

  - type: dropdown
    attributes:
      label: (If 'Yes') what was the outcome after Restarting?
      options:
        - "Please Select"
        - Returned to Normal, But cannot Reproduce the Bug - Provide Logs/Save File & Last Backup File
        - Returned to Normal, But was able to reproduce the Bug again - Clearly describe the steps needed for reproduction - Provide Logs/Save File
        - Still Bugged immediately after Reloading the Game - Provide Logs/Save File
        - Even worse after Reloading the Game - Explain how it got worse - Provide Logs/Save File
    validations:
      required: true

  - type: dropdown
    attributes:
      label: How is the Decimal Number Symbol normally Displayed to you In-Game?
      options:
        - "Please Select"
        - "v0.35.6 & $45.75 (Dot Point) - Provide Logs/Save File"
        - "v0,35,6 & $45,75 (Comma) - Provide Logs/Save File"
        - "Neither of the above - Please explain further - Provide Logs/Save File"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe what happened before the Bug
      description: A clear description of what happened before you experienced the Bug.
      placeholder: |
        Providing NOT Only the Bug itself in your Bug Report, but also the events and what you were doing leading up to the bug can make or break getting your bug fixed promptly
        Example; Everything was fine initially, I had taken part 3 PC's before but then after the 3rd, each one Vanished when I put it onto the Disassembly Desk
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear description of what the bug is you experienced
      placeholder: |
        Example of a poorly described bug; 'PC randomly vanished for no reason'
        Example of a well described bug; 'Each time I put a PC onto the Disassembly Desk it Vanishes, I've tried with multiple PCs and each one vanished, so it wasnt a random once off, other Items all work fine, Restarting doesnt fix the issue.'
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: Please provide steps needed to repeat this Bug - It's rare that a bug 'just happened for no reason' - Please try re-call what you had done and were doing before this bug occurred.
      placeholder: |
        EXAMPLE;
        1. Go to the Personal Computer.
        2. Open the Games Folder.
        3. Leave Games Folder Open and exit the PC.
        4. Go to Sleep.
        5. Go back to the Personal Computer.
        6. Games Folder is now gone and cannot be Opened again.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshot(s)/Video(s)
      description: Please upload screenshots and/or links to videos that help illustrate the issue (If unable to provide media type 'Not Applicable' or 'N/A' and **why** (ex; 'I missed the oppurtunity to capture the bug').
      placeholder: |
        Drag your Screenshot(s) below to upload them, Upload your video(s) to a Video Hosting service of choice (ie Youtube, Drive etc) and add the link(s) here.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Player Logs
      description: Provide your player logs - If unsure how - refer to the [How to create an effective Bug Report](https://github.com/FuryFight3r/ScrappingSimulator/wiki/How-to-Create-an-effective-Bug-Report#first-step)
      placeholder: |
        If you are unsure of where to find your Player Logs or Save File please refer to the [How to create an effective Bug Report](https://github.com/FuryFight3r/ScrappingSimulator/wiki/How-to-Create-an-effective-Bug-Report#first-step) Wiki before creating a Bug Report to ensure your report doesnt get closed without a resolution. Or consider using the In-Game Report [F8] feature which takes out the hard work of File Locating and Packing for you.
        Please Click here and then Drag your [Player.log] and [Player-prev.log] below to upload the files.
        You can also add your Save-File here by archiving [Player.log], [Player-prev.log] and [Scrapping_Simulator_Data.es3] into a Zip file and dragging it here, or Use the In-Game [F8] Bug Report Feature to have this done automatically.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |          
        > [!CAUTION]
        > Have you made sure to include Crucial Information Such as Logs/Save File, Screenshots (or a reason why you couldn't provide any), Bug Description, Reproductioon Steps, etc?
        > 
        > Please double check to make sure you are not missing any important information that could help fix your problem quickly.
        >
        > Otherwise your Bug Report Issue may be closed without a Resolution if doesnt provide enough information for me to Investigate
        >
        > If you are struggling with what to provide and how to provide Logs/Details etc refer to the [How to create an effective Bug Report](https://github.com/FuryFight3r/ScrappingSimulator/wiki/How-to-Create-an-effective-Bug-Report#first-step)

  - type: dropdown
    attributes:
      label: Do you feel the Bug can be fixed given the information you've provided? - If not consider including more Information
      options:
        - "No"
        - "Yes"
    validations:
      required: false