name: Bug Report Template
description: File a bug report using the Template
title: "[Bug]: <Add Title Here>"
labels: [BUG]
assignees: "FuryFight3r"
body:
  - type: markdown
    attributes:
        value: |
          If your Bug Report is in relation to an Object Disapearing or something else odd happening have you considered checking the Lost & Found Box next to your PC or the Commands panel (accessed by pressing [F1] or Tilde [~]) which may solve known bugs.

          If something is consistently breaking and needing a command to fix, then please post a Bug Report including the process on how to make the object consistently break.

          Thank you for submitting a bug report. Please search if your issue [already exists](https://github.com/FuryFight3r/ScrappingSimulator/labels/BUG) before submitting a report.


  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is - Try Include events leading upto the error.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: Steps we can take to get the exact same outcome as you
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: false
  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      description: A clear and concise description of what you expected to happen
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshot(s)/Video(s)
      description: If applicable, add Screenshots and or Videos to help explain the problem you are facing.
      placeholder: |
        Please Drag your Screenshot(s) below to upload them, please upload your video(s) to a Video Hosting service (ie Youtube) and add the link(s) here.
    validations:
      required: false
  - type: textarea
    id: console
    attributes:
      label: Console output
      description: While in-game press 'F5' to show the Console Log, Look for any recent red error(s), Make sure to click the error(s) to view the entire log and click [Copy] which will greatly help us find what went wrong.
      placeholder: |
        If you find any recent Error Logs that seem to match up with the issue you are facing, please post them here which will greatly speed up the fixing process.
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Player Logs
      description: If you are unable to locate any Errors in the Console please provide your Player Logs, which gives us a breif detail of your system specs and all the Console print outs for your your last 2 Game Launches
      placeholder: |
        Please Drag your Player.Log and Player-prev.log below to upload the files.
        You can also add your Save-File here by adding [Player.log], [Player-prev.log] and [Scrapping_Simulator_Data.es3] into a Zip folder and dragging it here.
        If you are unsure of where to find your Player Logs please refer to the [How to create an effective Bug Report](https://github.com/FuryFight3r/ScrappingSimulator/wiki/How-to-Create-an-effective-Bug-Report#first-step) Wiki
    validations:
      required: false
