name: Bug Report Template
description: File a bug report using the Template
title: "[Bug]: "
labels: [BUG]
assignees: "FuryFight3r"
body:
  - type: markdown
    attributes:
        value: |
        [PLEASE NOTE]

        Before proceeding with your bug report, have you explored the in-game bug reporting feature accessible by pressing [F8]? This feature is designed to streamline the reporting process by automatically bundling essential log files and save data. While it may seem like a minor inconvenience, providing these files significantly expedites the resolution of reported issues.

        Recently, I've encountered numerous user/system-specific reports coming in that may not manifest on every system, making them particularly challenging to address without comprehensive information. If you encounter an issue that appears isolated to your system, it's crucial to understand that resolving such 'phantom bugs' requires Player Logs most importantly with your Bug Report. Without this data, identifying and rectifying the problem becomes akin to chasing shadows, diverting resources and time from the game's development.

        Efforts are consistently made to ensure the game functions as intended before each update release. Granted, unforeseen complications can arise in this complex project and things can be overlooked at times - If a core mechanic or system is found to be dysfunctional, it's unlikely to affect the entire user base and often points to a user/system-specific bug rather than a global issue.

        One prevalent cause of known system-specific bugs is the usage of decimal numbers displayed with commas (e.g., v0,37 instead of v0.37 or $599,95 instead of $599.95), commonly observed in European regions. As I'm not located in Europe or regions utilizing comma-style decimals, addressing these issues necessitates understanding their specifics.

        Reports from users in such regions often cite difficulties loading save files, experiencing crashes during loading, or encountering missing data upon successful load. Without player logs, resolving these issues remains challenging since the majority of players—including myself—do not encounter them. Consequently, these issues are temporarily categorized as 'unfixable' until detailed logs are provided by affected users.

        [Other Info]

        If your bug report pertains to objects disappearing or falling through the ground, have you checked the Lost & Found Box adjacent to your Personal Computer? Additionally, for any other unusual occurrences, consider accessing the Commands panel (accessible via [F1] or Tilde [~]), which offers solutions for some known bugs.

        Persistent issues requiring frequent command usage for resolution are not typical. Commands are intended to address broken data, code death loops, or player stuck instances, rather than serve as a recurring means of repair. If you encounter such issues, please submit a bug report detailing the process to reproduce the bug consistently.
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear description of what the bug is you experienced - Try Include events leading upto the error.
      placeholder: |
        A good Report should include events leading up to the Bug not only just the Bug itself.
        Example of a poorly described bug; 'PC randomly vanished for no reason'
        Example of a well described bug; 'Each time I put a PC onto the Disassembly Desk it Vanishes, I've tried with multiple PCs and each one vanished so it wasnt a random once off, other Items all work fine, Restarting doesnt fix the issue.'
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: Please provide steps to get the exact same outcome as you - It's very rare that a bug 'just happened for no reason' 9/10 times there is a cause behind it and even sometimes very specific Steps involved to recreate the Issue - For example, Saving/Loading can be a great way fix some bugs, but on certain occasions it can be a cause for major issues, so if you recently Saved/Loaded to then find an issue that wasnt there before, consider including this crucial information in your report
      placeholder: |
        EXAMPLE;
        1. Go to the Personal Computer.
        2. Open the Games Folder.
        3. Leave Games Folder Open and exit the PC.
        4. Go to Sleep.
        5. Go back to the Personal Computer.
        6. Games Folder is now gone and cannot be Opened again.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshot(s)/Video(s)
      description: Consider providing Screenshot(s) and or Video(s) to help explain your issue.
      placeholder: |
        Drag your Screenshot(s) below to upload them, Upload your video(s) to a Video Hosting service of choice (ie Youtube) and add the link(s) here.
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Player Logs
      description: Please provide your player logs - This Field is now required due to recent refusal to provide logs for User/System Specific Issues
      placeholder: |
        Please Click here and then Drag your Player.Log and Player-prev.log below to upload the files.
        You can also add your Save-File here by adding [Player.log], [Player-prev.log] and [Scrapping_Simulator_Data.es3] into a Zip folder and dragging it here.
        If you are unsure of where to find your Player Logs or Save File please refer to the [How to create an effective Bug Report](https://github.com/FuryFight3r/ScrappingSimulator/wiki/How-to-Create-an-effective-Bug-Report#first-step) Wiki before creating a Bug Report.
    validations:
      required: true
