name: In-Game Bug Report Template
description: In-Game Bug Report Template
body:
  - type: markdown
    attributes:
      value: |
        > [!CAUTION] 
        > This Bug Report Template is designed for use within the ***In-Game Bug Report*** feature. Which can be accessed by pressing ***[F8]*** in-game. 
        > Using this Template outside the In-Game Bug Report Interface may result in inaccurately filled fields that are auto filled by the Game, resulting in automatic closure of the report.

        > [!IMPORTANT]
        > First time Creating a Bug Report for Scrapping Simulator? or does all this look New to you?
        > Please checkout the Button Link below to ensure that your Report doesn't get closed without a Resolution.
        > 
        > If you've read this Guide in the past (Prior to April 2024), have another look as it has changed a lot since, it's been Reworked and also now provides some Examples & more Tips to help you make a great Bug Report that likely will be fixed very promptly.

        [![How to create an Effective Bug Report](https://i.imgur.com/9ocGiJF.png)](https://github.com/FuryFight3r/ScrappingSimulator/wiki/How-to-Create-an-effective-Bug-Report#first-step)
        
        > [!TIP]
        > If you cannot use the In-Game Bug Reporting feature please create a [[Manual Bug Report]](https://github.com/FuryFight3r/ScrappingSimulator/issues/new?assignees=FuryFight3r&labels=BUG&projects=&template=bugReport.yaml&title=%5BBug%5D%3A+) Describing what is happening - If you do not wish to use the In-Game Reporting Feature, please create a [[Suggestion]](https://github.com/FuryFight3r/ScrappingSimulator/issues/new?assignees=FuryFight3r&labels=Suggestion&projects=&template=suggestion.yaml&title=%5BSuggestion%5D%3A+%3CAdd+Title+Here%3E) on how I can improve it and or make it easier. 

        ---

        # Bug Report

  - type: dropdown
    attributes:
      label: Have you tried Restarting the Game?
      options:
        - "Please Select"
        - "No"
        - "Yes"
        - "Cannot Save/Exit due to bug"
    validations:
      required: true

  - type: dropdown
    attributes:
      label: (If 'Yes') what was the outcome after Restarting?
      options:
        - "Please Select"
        - Returned to Normal, But cannot Reproduce the Bug
        - Returned to Normal, But was able to reproduce the Bug again
        - Still Bugged immediately after Reloading the Game
        - Even worse after Reloading the Game
    validations:
      required: true

  - type: dropdown
    attributes:
      label: How is the Decimal Number Symbol normally Displayed to you In-Game?
      options:
        - "Please Select"
        - "v0.35.6 & $45.75 (Dot Point)"
        - "v0,35,6 & $45,75 (Comma)"
        - "Neither of the above - Please explain further"
    validations:
      required: true

  - type: textarea
    id: bugfile
    attributes:
      label: Automatically Generated Bug Zip File
      description: Please drag and drop the generated zip file (PlayerName_SavedGameVersion_CurrentGameVersion_BugReport.zip) into this field.
      placeholder: Drag & Drop the Generated Zip File Here - Click this Box First to activate and allow dropping of File.
    validations:
      required: true

  - type: textarea
    id: bug_description
    attributes:
      label: Describe the bug
      description: A clear description of what the bug is you experienced
      placeholder: |
        Example of a poorly described bug; 'PC randomly vanished for no reason'
        Example of a well described bug; 'Each time I put a PC onto the Disassembly Desk it Vanishes, I've tried with multiple PCs and each one vanished, so it wasn't a random once off, other Items all work fine, Restarting doesn't fix the issue.'
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Outline the steps needed to reproduce the bug.
      placeholder: |
        Example;
        1. Go to Hardware Store.
        2. Purchase Radio.
        3. Open Box Containing Radio
        4. Radio Won't Appear
        5. Error '......' was produced in the [F5] Menu
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshot(s)/Video(s)
      description: Please upload screenshots and/or provide links to videos that help illustrate the issue (If unable to provide media type 'Not Applicable' or 'N/A' and why).
      placeholder: |
        Drag your screenshot(s) here to upload. For videos, please provide links to video host services like YouTube (Click this box first to activate the Text Box).
    validations:
      required: true

  - type: markdown
    attributes:
      value: |          
        > [!CAUTION]
        > Have you made sure to include Crucial Information Such as Logs, Description & Reproductioon Steps?
        > 
        > Please double check to make sure you are not missing any important information that could help fix your problem quickly.
        >
        > Otherwise your Bug Report Issue may be closed without a Resolution if doesn't provide enough information for me to Investigate
        >
        > If you are struggling with what to provide and how to provide Logs/Details etc refer to the [How to create an effective Bug Report](https://github.com/FuryFight3r/ScrappingSimulator/wiki/How-to-Create-an-effective-Bug-Report#first-step)

  - type: dropdown
    attributes:
      label: Do you feel the Bug can be fixed given the information you've provided? - If not consider including more Information About the Bug and Before the Bug
      options:
        - "No"
        - "Yes"
    validations:
      required: false
