name: Suggestion Template
description: Give a suggestion using the Template
title: "[Suggestion]: <Add Title Here>"
labels: [Suggestion]
body:
  - type: markdown
    attributes:
        value: |
          Thank you for taking the time to give us your suggestion! Before we get started, you might want to check if someone else has already suggested it. [Check Existing Suggestions](https://github.com/FuryFight3r/ScrappingSimulator/labels/Suggestion)
  - type: textarea
    id: description
    attributes:
      label: Suggestion;
      description: What would you like to suggest for Scrapping Simulator?
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Why is this a good suggestion?
      description: Please describe why you think this suggestion would work well with Scrapping Simulator
    validations:
      required: true